# Generated by Django 3.0.3 on 2020-03-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Riddle',
            new_name='Catalog',
        ),
    ]
