# Generated by Django 3.0.3 on 2020-03-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200304_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='Addres',
            new_name='Address',
        ),
    ]
